version: '{build}'
os: Visual Studio 2019
build_script:
- ps: ./build.ps1
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: XPg93XhKCJqXKFX3CuwNvvcZTuv/IbyclwKcGqHPrrnQe2SByTbDJ+VflrHXSPl1
  skip_symbols: true
  artifact: /artifacts\/packages\/.+\.nupkg/
